<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'day01' => '/Day01.php',
                'day02' => '/Day02.php',
                'day03' => '/Day03.php',
                'day04' => '/Day04.php',
                'day05' => '/Day05.php',
                'day06' => '/Day06.php',
                'day07' => '/Day07.php',
                'day08' => '/Day08.php',
                'day09' => '/Day09.php',
                'day10' => '/Day10.php',
                'day11' => '/Day11.php',
                'day12' => '/Day12.php',
                'day13' => '/Day13.php',
                'day14' => '/Day14.php',
                'day15' => '/Day15.php',
                'day16' => '/Day16.php',
                'day17' => '/Day17.php',
                'day18' => '/Day18.php',
                'day19' => '/Day19.php',
                'day20' => '/Day20.php',
                'day21' => '/Day21.php',
                'day22' => '/Day22.php',
                'iday' => '/iDay.php',
                'inputloader' => '/InputLoader.php',
                'intcodeprocessor' => '/IntCodeVM.php',
                'intcodevm' => '/IntCodeVM.php',
                'permutationiterator' => '/PermutationIterator.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
